### ISSUE TITLE
Elasticsearch: pulling it out of container

### ISSUE THREAD

**Issue by BretFisher** [Code4HR/hercules#2]
I'm thinking it'll work better in the long term of this project to have ES in it's own container for test, and possibly its own HA server set in prod. Once we decide on cloud architecture/vender we could make this a task to do for prod buildout so ES can stay persistent. I would recommend [AWS AES](https://aws.amazon.com/elasticsearch-service/) to keep us out of managing servers but not hearing the greatest things about this brand new service... Anyone already have thoughts on ES design?

**Comment by blackhatbrigade** [comment]
I've been looking into this as well.  Either way, I 100% agree it needs pulled out of the repo.  That was only ever a hack to allow propagation of data amongst the team without having to run the cron jobs manually each time you started up the container.

That being said, it is extremely usefully having that data hosted somewhere so that during container build it can be pulled in for development usage.  Preferably where the Production ES instance maintains the data.  I just don't have any solutions for this.  I know ES has some cross network redundancy ability, but not sure if this can be leveraged to help us out.

Needs more R&D.  I welcome any thoughts.

**Comment by BretFisher** [comment]
For now, Bret will setup multiple ES containers in DO for everyone to use for dev/test/prod. Then we can keep this data and ES out of hercules repo.

**Comment by BretFisher** [comment]
Elasticsearch is now available at http://hercules.code4hr.org:33366
