### ISSUE TITLE
Food Inspection Data Gone

### ISSUE THREAD

**Issue by asedarski** [Code4HR/hercules#54]
It appears the OpenHealthInspection data is no longer being supported. The domain openhealthinspection.com is no longer available. 

-- Questions:
Will Code4HR be bringing back the Open Health Inspection support?

**Comment by BretFisher** [comment]
Yes, likely, maybe a different URL, seems we let domain expire. It's being discussed in the #open-health slack channel. The day was quite old (nearly a year) anyway due to the site we were scraping from changing their interface, thus breaking our scraper (at least that's how I think it went). @ttavenner and @wbprice may have more info.

**Comment by ttavenner** [comment]
The open health inspection data is back up at this URL: http://ohi-api.code4hr.org. We are also very close to completing a re-write of the scraper which will get new data flowing into the system.

**Comment by asedarski** [comment]
I keep getting a 502 on the inspections endpoint. Is there something I'm missing or is the API not currently functional?

**Comment by ttavenner** [comment]
I'm not sure what was happening yesterday but it seems to be fully functional today.

**Comment by hop-along-polly** [comment]
Resolved by PR#71
