### ISSUE TITLE
Pull data from BLS api

### ISSUE THREAD

**Issue by josibake** [Code4HR/hercules#55]

**Comment by blackhatbrigade** [comment]
Did you by chance verify that the data we wanted is even on BLS?  The closest area I can find to Hampton Roads is Washington DC.  I started working on this with the assumption that since it was changed from the census data, you guys had found more relevant data with BLS.  But I'm not finding ANY.

End result is I just wasted 2 afternoons working on getting data from an API that doesn't have data we can use.

Reference:
Areas supported by BLS: http://download.bls.gov/pub/time.series/ap/ap.area

**Comment by asedarski** [comment]
Closing this since the data is not useable
